apiVersion: v1
kind: Service
metadata:
  name: hellok8s
  labels:
    name: ok
spec:
  selector:
    app: hellok8s
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  type: {{ .Values.service.type }}

